### ISSUE TITLE
As a player in a game of Exploding Kittens, I want to send friendship requests to other registered users so we can play together and know when they are online.

### ISSUE THREAD

**Issue by JorgeOrtizV** [sopra-fs24-group-17/server#1]
- [ ] In the profile it is possible to send a friendship request to the given user.
- [ ] A notification is obtained if the other user accepts the invitation. 
- [ ] A users friends shall be viewable in a dedicated overview page, including their online status.
- [ ] Users shall be able to enable specific profile information such as email address for friends only.
- [ ] A user shall get in-app notification when their friends are online or earned new achievements.

## Server-Side Tasks
- [x] sopra-fs24-group-17/server#67
- [x] sopra-fs24-group-17/server#68
- [x] sopra-fs24-group-17/server#69
- [x] sopra-fs24-group-17/server#70
- [x] sopra-fs24-group-17/server#71
- [x] sopra-fs24-group-17/server#72
- [x] sopra-fs24-group-17/server#73

## Client-Side Tasks
- [x] sopra-fs24-group-17/client#6
- [x] sopra-fs24-group-17/client#7
- [x] sopra-fs24-group-17/client#8
- [x] sopra-fs24-group-17/client#9
- [x] sopra-fs24-group-17/client#31
- [x] sopra-fs24-group-17/client#51
- [x] sopra-fs24-group-17/client#54
- [x] sopra-fs24-group-17/client#101
