### ISSUE TITLE
As a logged-in user, I want to edit my own user profile to set/update my personal information.

### ISSUE THREAD

**Issue by JorgeOrtizV** [sopra-fs24-group-17/server#2]
- [ ] By clicking on an edit button in the user-profile view, you are able to change the user’s username, birthday, password and set an choose an avatar for the game.
- [ ] A registered user can only change their own profile and not profiles of other users.
- [ ] After changing and saving the data, the user is redirected to the profile page and the new/changed data is displayed

## Server-Side Tasks
- [x] sopra-fs24-group-17/server#43
- [x] sopra-fs24-group-17/server#44
- [x] sopra-fs24-group-17/server#45
- [x] sopra-fs24-group-17/server#46
- [x] sopra-fs24-group-17/server#47
- [x] sopra-fs24-group-17/server#48
- [x] sopra-fs24-group-17/server#49

## Client-Side Tasks
- [x] sopra-fs24-group-17/client#10
- [x] sopra-fs24-group-17/client#11
- [x] sopra-fs24-group-17/client#13
- [x] sopra-fs24-group-17/client#12
- [x] sopra-fs24-group-17/client#14
- [x] sopra-fs24-group-17/client#44
