### ISSUE TITLE
As a registered user, I want to initiate a new game of Exploding Kittens so that I can play with other users.

### ISSUE THREAD

**Issue by JorgeOrtizV** [sopra-fs24-group-17/server#5]
* The "New Game" button on the dashboard creates a new game session and displays a waiting room.
* The user can set the game as "public" or "private" when creating a new game.
* For private games, the user receives a unique code to share with selected users for joining the game.
* The interface shows the number of players joined and starts the game once the minimum player count is reached and the host confirms to start.
* Per default the minimum player count shall be two but the user creating the session shall have the optionality to extend this minimal requirement up to five users.
* If the game session fails to create, an error message is displayed, and the user remains on the dashboard.

## Server-Side Tasks
- [x] sopra-fs24-group-17/server#79
- [x] sopra-fs24-group-17/server#80
- [x] sopra-fs24-group-17/server#81
- [x] sopra-fs24-group-17/server#82

## Client-Side Tasks
- [x] sopra-fs24-group-17/client#15
- [x] sopra-fs24-group-17/client#16
- [x] sopra-fs24-group-17/client#18
- [x] sopra-fs24-group-17/client#22
- [x] sopra-fs24-group-17/client#23
- [x] sopra-fs24-group-17/client#24
