### ISSUE TITLE
As a totally new player of the game "Exploding Kittens", I want the platform to have an interactive guide through tutorial so I can learn to play as fast as possible.

### ISSUE THREAD

**Issue by JorgeOrtizV** [sopra-fs24-group-17/server#8]
- [ ] When a new user logins for the first time, the application prompts if the user would like to take the tutorial before playing.
- [ ] Even though the user rejects to check the tutorial, it can be accessed at any other time, but there will be no more prompting.
- [ ] During the tutorial the user is explained the specifics of the game (what each card does, etc.) and how the user interface work.
- [ ] The rules of the game shall be accessible at any time during the game by means of a small overview that can be displayed.

## Server-Side Tasks
- [x] sopra-fs24-group-17/server#91
- [x] sopra-fs24-group-17/server#92
- [x] sopra-fs24-group-17/server#93

## Client-Side Tasks
- [x] sopra-fs24-group-17/client#25
- [x] sopra-fs24-group-17/client#26
- [x] sopra-fs24-group-17/client#27
- [x] sopra-fs24-group-17/client#28
- [x] sopra-fs24-group-17/client#29
- [x] sopra-fs24-group-17/client#30
